package com.kontenery.model.enums

enum class ScreenType {
    COMPACT, MEDIUM, EXPANDED
}

enum class CurrentScreen {
    CLIENTS_LIST, CLIENT_DATA, CLIENT_FINANCE, CLIENT_CONTRACTS,
    PRODUCTS_LIST, ADD_PRODUCT, PRODUCT_DATA,
    ADD_CONTRACT, EDIT_CONTRACT,
    ADD_INVOICE,
    PAYMENT_MENU, BANK_ACCOUNT_MENU, PAYMENT_FORM, UPLOAD_PAYMENTS,
    FINANCES,
    UTILITY,

}